name: 刷步数

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 12 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 初始化Python
      uses: actions/setup-python@v5
        python-version:3.11
    - name: 开始
      run: |
        pip install requests
        pmode='${{ secrets.PMODE }}'
        pkey='${{ secrets.PKEY }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${pmode}
        ${pkey}
        ${user}
        ${pwd}
        ${step}
        EOF
