name: 刷步数

on:
  push:
    branches: [主]
  pull_request:
    branches: [主]
  schedule:
    - cron: '0 12 * * *'  # 添加引号
  watch:  # GitHub 没有 "watch" 事件类型
    types: [started]  # 已启动事件可能不适用于 watch

jobs:
  构建:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # 修复第19行错误 - 关键修正点
      - name: 初始化Python
        uses: actions/setup-python@v5  # 修复缩进和使用英文关键字
        with:
          python-version: "3.11"  # 添加引号
      
      - name: 开始
        run: |  # 修复环境变量语法
          pip install requests
          pmode="${{ secrets.PMODE }}"
          pkey="${{ secrets.PKEY }}"
          user="${{ secrets.USER }}"
          pwd="${{ secrets.PWD }}"
          step="${{ secrets.STEP }}"
          
          python3 main.py "$pmode" "$pkey" "$user" "$pwd" "$step"
