名字：刷步数

在输入：
  推输入：
    分支：[ 主 ]
  拉取请求输入：
    分支：[ 主 ]
  日程安排输入：
    - cron: 0 12 * * *
  观看输入：
    类型： 已开始

工作：
  构建：
    运行于：ubuntu-latest

    步骤输入：
    - 使用：actions/checkout@v4
    - 名称: 初始化Python
      使用： actions/setup-python@v5
      和：
        python-version： 3.11
    - 名称: 开始
      运行： |
        pip install requests
        pmode='${{ secrets.PMODE }}'
        pkey='{{ secrets.PKEY }}'
        用户='{{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <
        ${模式}
        ${公钥}
        ${用户}
        ${当前工作目录}
        ${步}
        文件结束
